name: Tamarin Verification CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        bash .github/workflows/setup-deps.sh
    - name: Verify
      run: |
        tamarin-prover --prove broadcast_protection.spthy
